### ISSUE TITLE
로딩이 느립니다.

### ISSUE THREAD

**Issue by dodo4114** [Island-dev/signal-homepage#92]
제 컴퓨터의 문제일 수도 있지만,
폰트가 깨지는 등 로딩이 느림으로써 발생하는 문제가 생깁니다.
- 로딩을 빠르게 하거나
- 로딩 대기 표시를 만들거나
하면 될 것 같습니다.

**Comment by mh960110** [comment]
https://www.w3schools.com/howto/howto_css_loader.asp
참고해서 로딩 대기 표시 만들겠습니다.

**Comment by mh960110** [comment]
@dodo4114 deploy 후 로딩 속도 빨라지면 닫겠음~

**Comment by mh960110** [comment]
Resolved by #100
