### ISSUE TITLE
북마크 전용 이미지 생성

### ISSUE THREAD

**Issue by ddal0115** [Island-dev/signal-homepage#93]
북마크 생성 시 뜨는 이미지를 사이즈에 맞게 생성하여,
meta 태그를 수정해 이미지를 적용합니다.

**Comment by dodo4114** [comment]
단순히 og:image 뿐만 아니라 twitter:image에 대해서도 변경을 가해야 하는 것으로 보입니다.

![image](https://user-images.githubusercontent.com/52357676/96365320-bc6eea80-117a-11eb-8528-c52133925f09.png)
